name: vector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.7
  - conda: 
    - root # install if needed (huge package)
  - pip
  - pip:
    - pandas==1.5.0
    - scikit-learn==1.1.2
    - numpy==1.23.3
    - uproot==4.2.3
    - awkward==1.10.1
    - matplotlib==3.1.2
    - seaborn==0.12.0
    - statsmodels==0.13.2
    - tqdm==4.64.1
    - scipy==1.9.2
    - shap==0.41.0
    - pickleshare==0.7.5
    - plotly==5.10.0
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - matplotlib-inline==0.1.3
    - notebook==6.4.11
    - iminuit==2.17.0
    - pytest==7.1.3